type User {
    _id: String!,
    firstName: String!,
    lastName: String!,
    email: String!,
    country: String!,
}

type Recipe {
    _id: String!,
    country: String!,
    ingridients: [String],
    spiceLevel: Float,
    process: String,
    userId: String!,
}

type Country {
    _id: String!,
    code: String!,
    name: String!,
}



type Query {
    recipie: [Recipe],
    country: [Country],
    user: [User]
}
